### ISSUE TITLE
Crash when closing window while in Physics Sandbox

### ISSUE THREAD

**Issue by apples** [xxAtrain223/ArkAngel#5]
```
Assertion failed!
File: ArkAngel/src/GameStateManager.cpp, Line 73
```

The call to `engine->ScriptEngine->RemoveConfigGroup(suid.c_str())` is failing because there are still references to the group.

**Comment by xxAtrain223** [comment]
Steps to reproduce.
1. Launch ArkAngel.
2. Enter the Physics Sandbox.
3. Exit the Physics Sandbox.
